version: '3.7'

services:

  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Geslo.01
    ports:
      - "3307:3306"
    volumes:
      - ds_databases:/var/lib/mysql
    networks:
      - jupyter-network

  jupyter:
    build: ./jupyter    
    depends_on:
      - mysql
    restart: always
    ports:
      - "8888:8888"
    networks:
      - jupyter-network
    environment:
      NB_USER: jupyter
    volumes:
      - ./notebooks:/home/jovyan/work/home/jovyan/work

networks:
  jupyter-network:
    driver: bridge

volumes:
   ds_notebooks: 
   ds_databases: